### ISSUE TITLE
Image caching

### ISSUE THREAD

**Issue by catchakos** [ernesto-elsaesser/WebArchiver#1]
Should referenced image caching work out of the box for Xcode 11 / iOS 13? 

When archiving the test page of the OfflineWebView demo project, I see that an image is added as a WebArchiveResource. When unarchiving while offline though, the image at the bottom does not get displayed. 
By inspecting the archived HTML I see that the image still points to the remote resource. 
Should the HTML be modified to point to some local image reference or what should I do to be able to display the archived images when offline?

**Comment by catchakos** [comment]
this small fix #2 seems to solve the problem

**Comment by ernesto-elsaesser** [comment]
Hi catchakos, first of all thank you so much for taking the time to analyze and fix this issue! 

I was somehow assuming that `URL` objects would get encoded as strings, but looks like they don't (https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/URL.swift#L1221). Maybe some internals changed since I first wrote that code ... Anyhow, your fix ensures that the `WebResourceURL` fields are filled with strings, not sub-dictionaries, which is how it should be. Will merge it immediately. And sorry for taking so long to respond, should have merged this months ago ...
